version: '3.8'  # Docker Compose 파일의 버전 설정

networks:  # 네트워크 정의
  monitor:  # 'monitor'라는 이름의 네트워크 생성
    driver: bridge  # 기본 브리지 네트워크 드라이버 사용

services:  # 서비스 정의
  redis:  # Redis 서비스 설정
    container_name: redis  # 컨테이너 이름 설정
    image: redis:7.4  # Redis 이미지 버전 7.4 사용
    ports:
      - "6380:6379"  # 호스트와 컨테이너 간 포트 매핑 (6379 포트)
    command: ["redis-server", "--requirepass", "pk2258"]  # 비밀번호 설정
    networks:
      - monitor  # 'monitor' 네트워크에 연결
    restart: always  # 컨테이너가 종료되면 자동으로 재시작
