server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  profiles:
    active: dev
    include: secret
  data:
    redis:
      port: ${redis.port}
      host: ${redis.host}
      password: ${redis.password}
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    hikari:
      auto-commit: false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

jwt:
  token-validity-in-seconds: 86400 # JWT 토큰의 유효 기간
  issuer: eCommerce-Web-Service

logging:
  level:
    com.example.ecommercewebservice: DEBUG
    org.springframework.security: INFO